//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptionMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceExceptionMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Shared.Exceptions.ResourceExceptionMessages", typeof(ResourceExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UNKNOWN_ERR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERR", resourceCulture);
            }
        }
        
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        public static string INVALID_USERNAME {
            get {
                return ResourceManager.GetString("INVALID_USERNAME", resourceCulture);
            }
        }
        
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string USERNAME_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USERNAME_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        public static string INVALID_TITLE {
            get {
                return ResourceManager.GetString("INVALID_TITLE", resourceCulture);
            }
        }
        
        public static string INVALID_SUBTITLE {
            get {
                return ResourceManager.GetString("INVALID_SUBTITLE", resourceCulture);
            }
        }
        
        public static string INVALID_IMAGE {
            get {
                return ResourceManager.GetString("INVALID_IMAGE", resourceCulture);
            }
        }
        
        public static string USERNAME_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USERNAME_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        public static string INVALID_SOURCE_ID {
            get {
                return ResourceManager.GetString("INVALID_SOURCE_ID", resourceCulture);
            }
        }
        
        public static string INVALID_TEMPLATE_ID {
            get {
                return ResourceManager.GetString("INVALID_TEMPLATE_ID", resourceCulture);
            }
        }
        
        public static string CANNOT_DELETE_APPROVED {
            get {
                return ResourceManager.GetString("CANNOT_DELETE_APPROVED", resourceCulture);
            }
        }
        
        public static string STATUS_IS_ALREADY {
            get {
                return ResourceManager.GetString("STATUS_IS_ALREADY", resourceCulture);
            }
        }
        
        public static string ITEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ITEM_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string SOURCE_NOT_APPROVED {
            get {
                return ResourceManager.GetString("SOURCE_NOT_APPROVED", resourceCulture);
            }
        }
        
        public static string TEMPLATE_NOT_APPROVED {
            get {
                return ResourceManager.GetString("TEMPLATE_NOT_APPROVED", resourceCulture);
            }
        }
        
        public static string MISSING_BODY {
            get {
                return ResourceManager.GetString("MISSING_BODY", resourceCulture);
            }
        }
        
        public static string EMPTY_ITEM {
            get {
                return ResourceManager.GetString("EMPTY_ITEM", resourceCulture);
            }
        }
        
        public static string INVALID_REPLACES {
            get {
                return ResourceManager.GetString("INVALID_REPLACES", resourceCulture);
            }
        }
        
        public static string NOT_ENOUGH_SOURCES {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_SOURCES", resourceCulture);
            }
        }
    }
}
